[versions]
minSdk = "26"
targetSdk = "36"
versionCode = "2"
versionName = "1.0.2"
compile-sdk-version = "36"
accompanistPermissions = "0.37.3"
coreSplashscreen = "1.0.1"
countryPicker = "2.1.0"
firebaseBom = "34.1.0"
libphonenumber = "9.0.12"
playServicesLocation = "21.3.0"
secretsGradlePlugin = "2.0.1"
swipe = "1.3.0"

activity-compose = "1.10.1"
core-ktx = "1.17.0"
androidx-material = "1.7.8"
lifecycle-runtime-ktx = "2.8.7" # crushed
composeBom = "2025.03.00"
compose-version = "1.8.2"
android-application-version = "8.12.1"
kotlin-android-version = "2.2.10"
hilt-version = "2.57.1"
coroutine-version = "1.10.2"
hilt-compose-navigation-version = "1.2.0"
ksp-version ="2.2.0-2.0.2"
dagger-version = "2.57.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.3.0"
espresso-core = "3.7.0"
appcompat = "1.7.1"
material = "1.12.0"
voyager = "1.0.1"
koin-compose-version = "1.0.4" # SSL peer shut down incorrectly
koin-android-version = "3.5.3" # SSL peer shut down incorrectly
splash-version = "1.0.1"
kotlin-date-time = "0.7.1"
datastore-version = "1.1.7"
ktor-version = "3.2.3"
kotlinx-json-serialization = "1.9.0"
coil = "2.7.0"
room_version = "2.7.2"
pagingCompose = "3.3.6"
mapsCompose = "6.7.2"
playServicesMaps = "19.2.0"
jsoup = "1.21.2"


[libraries]
# ui
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "androidx-material" }
country-picker = { module = "com.github.arpitkatiyar1999:Country-Picker", version.ref = "countryPicker" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
#firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-crashlytics-ndk = { module = "com.google.firebase:firebase-crashlytics-ndk" }
google-firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumber" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
secrets-gradle-plugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }
splash-screen = { module = "ndroidx.core:core-splashscreen", version.ref = "splash-version" }

# compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-test-mainifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-materialIcons = { module = "androidx.compose.material:material-icons-extended"}#, version.ref = "compose-version" }

# hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-version" }
hilt-ksp = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-version" }
hilt-compose-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-compose-navigation-version" }
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "dagger-version" }

# coroutines
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine-version" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# voyager
swipe = { module = "me.saket.swipe:swipe", version.ref = "swipe" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-screenModel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
voyager-bottomSheetNavigator = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyager" }
voyager-tabNavigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }
#voyager-hilt = { module = "cafe.adriel.voyager:voyager-hilt", version.ref = "voyager" }

# koin
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose-version" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-android-version" }
koin-insert = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-android-version" }


# kotlin
kotlin-date-time = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-date-time" }
kotlinx-json-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-json-serialization" }

# datastore
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-version" }

# ktor-client
ktor-client = { module = "io.ktor:ktor-client-core", version.ref = "ktor-version" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor-version" }
ktor-cio-engine = { module = "io.ktor:ktor-client-cio", version.ref = "ktor-version" }
ktor-loging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor-version" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-version" }
ktor-json-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor-version" }
ktor-gson = { module = "io.ktor:ktor-serialization-gson", version.ref = "ktor-version" }
#ktor-client-json = { module = "io.ktor:ktor-client-json", version.ref = "ktor-version" }
#ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor-version" }
#ktor-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "ktor-version" }

# coil
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

#jsoup
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }

# maps compose
maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "mapsCompose" }

# room
room = { module = "androidx.room:room-runtime", version.ref = "room_version" }
room-coroutine = { module = "androidx.room:room-ktx", version.ref = "room_version" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room_version" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room_version" }
androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "pagingCompose" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "pagingCompose" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }



[bundles]
compose = [
    "compose-ui",
    "compose-ui-graphics",
    "compose-ui-preview",
    "compose-material3",
    "compose-ui-tooling",
    "compose-ui-test-mainifest"
]

voyager = [
    "voyager-navigator",
    "voyager-screenModel",
    "voyager-bottomSheetNavigator",
    "voyager-tabNavigator",
    "voyager-transitions",
    "voyager-koin"
]

room = ["room", "room-coroutine", "room-paging"]

[plugins]
android-application = { id = "com.android.application", version.ref = "android-application-version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android-version" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-version" }
#hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt-version" }
androidLibrary = { id = "com.android.library", version.ref = "android-application-version" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-version" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-android-version" }
